[package]
name = "dodge_the_rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.3.4", features = ["experimental-wasm", "lazy-function-tables"] }
